[package]
name = "whitepulse"
version = "0.1.1"
authors = ["makr17 <bracher@gmail.com>"]

[dependencies]
getopts = "0.2"
rand = "0.3"
time = "0.1"
houselights = { git = "https://github.com/makr17/houselights.git" }
